### ISSUE TITLE
A few little issues

### ISSUE THREAD

**Issue by mvdan** [pecigonzalo/pre-commit-shfmt#1]
Hey! I just came across this repo and noticed a few small issues.

* You match `*.sh` - what about `*.bash` and shell scripts without extension? If you run `shfmt` on a directory, it will automatically use only shell files, even if they have no extension, by looking for shebangs.
* Instead of `for file in "$@"; do shfmt -l -i 4 -w "$file"; done` just do `shfmt <opts> "$@"` (or a directory, as explained above)
* This tool is hard-coding `-i 4`?

**Comment by pecigonzalo** [comment]
@mvdan Thanks for the feedback
* That is correct, although I would say its standard to have `.sh` on most bash/sh/etc files, if `shfmt` detects that then ill give it a try.
* About `-i 4` yes its hard coded, I can put a VAR over there to allow for config if `pre-commit` allows me to. 

Ill give this a look soon, otherwise feel free to submit a PR

**Comment by notjames** [comment]
This seems to be a good one-liner you can use to find shell scripts in your repo:

```shell
find . -type f \( -name "*" ! -path "./.[a-zA-Z]*/*" ! -wholename './.[a-zA-Z]*' \) -exec file {} \; | \
grep -Pi 'shell script' | \
cut -d : -f 1`
```

**Comment by pecigonzalo** [comment]
Updated the hook to find all shell files from the ones provided and added indent as a parameter.

Let me know if this helps :D
